"""Add homework system

Revision ID: 357e95291bb2
Revises: 37c7415a117e
Create Date: 2026-02-18 22:53:48.683106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357e95291bb2'
down_revision: Union[str, Sequence[str], None] = '37c7415a117e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_homework_class_due', 'homework', ['class_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_homework_class_id'), 'homework', ['class_id'], unique=False)
    op.create_index(op.f('ix_homework_due_date'), 'homework', ['due_date'], unique=False)
    op.create_index(op.f('ix_homework_id'), 'homework', ['id'], unique=False)
    op.create_index(op.f('ix_homework_is_deleted'), 'homework', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_homework_teacher_id'), 'homework', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homework_teacher_id'), table_name='homework')
    op.drop_index(op.f('ix_homework_is_deleted'), table_name='homework')
    op.drop_index(op.f('ix_homework_id'), table_name='homework')
    op.drop_index(op.f('ix_homework_due_date'), table_name='homework')
    op.drop_index(op.f('ix_homework_class_id'), table_name='homework')
    op.drop_index('idx_homework_class_due', table_name='homework')
    op.drop_table('homework')
    # ### end Alembic commands ###
